"""Game settings and constants"""

# Display
NATIVE_W = 320
NATIVE_H = 180
SCALE = 3
WINDOW_W = NATIVE_W * SCALE
WINDOW_H = NATIVE_H * SCALE
FPS = 60

# Tile / World
TILE_SIZE = 16
ROOM_WIDTH = 256  # 16 tiles
ROOM_HEIGHT = 144  # 9 tiles
ROOM_CENTER_X = ROOM_WIDTH // 2
ROOM_CENTER_Y = ROOM_HEIGHT // 2

# Room spacing (matches Unity offsets)
ROOM_X_OFFSET = 288
ROOM_Y_OFFSET = 160

# Colors
COLOR_BG = (34, 32, 52)
COLOR_FLOOR = (60, 56, 84)
COLOR_WALL = (80, 76, 110)
COLOR_DOOR = (120, 100, 80)

# Game States
STATE_MENU = 0
STATE_PLAY = 1
STATE_PAUSE = 2
STATE_GAMEOVER = 3
STATE_VICTORY = 4

# Room Types
ROOM_START = 0
ROOM_NORMAL = 1
ROOM_END = 2
ROOM_SHOP = 3
ROOM_CHEST = 4
ROOM_BOSS = 5

# Enemy Types
ENEMY_BLOB = 0
ENEMY_COWARD = 1
ENEMY_DUMB_SHOOTER = 2
ENEMY_FIRE = 3
ENEMY_MACHINE_GUN = 4
ENEMY_SKELETON = 5

# Pickup Types
PICKUP_COIN = 0
PICKUP_HEALTH = 1
PICKUP_GUN = 2

# Gun Types
GUN_PISTOL = 0
GUN_SHOTGUN = 1
GUN_MACHINE_GUN = 2

# Directions
DIR_UP = 0
DIR_RIGHT = 1
DIR_DOWN = 2
DIR_LEFT = 3
